# Deck
from src.view.constants.ui_constants import MEDIUM_CARD_SIZE

ROW_COUNT = 2
COL_COUNT = 3
CARDS_PER_PAGE = ROW_COUNT * COL_COUNT
CARD_MARGIN = 20

COMM_LABEL_POS = (960, 150)

CARDS_Y = 270
COMM_Y = CARDS_Y - 90
TOP_BUTTONS_Y = 80
STATS_Y = 600

LEFT_START_POS = (70, CARDS_Y)
RIGHT_START_POS = (1180, CARDS_Y)

LEFT_LABEL_POS = (70, 150)
RIGHT_LABEL_POS = (1675, 150)

SCROLLBAR_WIDTH = 18
SCROLLBAR_HEIGHT = ROW_COUNT * (MEDIUM_CARD_SIZE[1] + CARD_MARGIN) - CARD_MARGIN
SCROLL_WIDTH = 24
LEFT_SCROLLBAR_POS = (LEFT_START_POS[0] - CARD_MARGIN - SCROLLBAR_WIDTH, LEFT_START_POS[1])
RIGHT_SCROLLBAR_POS = (RIGHT_START_POS[0] + COL_COUNT * (MEDIUM_CARD_SIZE[0] + CARD_MARGIN) + SCROLLBAR_WIDTH, RIGHT_START_POS[1])